# -*- coding: utf-8 -*-
"""penguin_eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14-_lmKnRkwaYZzRKtqZYL9X4m0ZDrGnH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

import os
path = "/content/drive/MyDrive/기계학습"
os.listdir(path)

df = pd.read_csv(path + '/penguins_size.csv')

df.info()

df.describe()

df.isnull().sum()

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist() # 수치형 컬럼
tf_columns = df.select_dtypes(include=['object']).columns.tolist() # 범주형 컬럼

# 히스토그램을 그릴 서브플롯 생성
plt.figure(figsize=(15, 15))
for i, column in enumerate(numeric_columns, start=1):
    plt.subplot(5, 5, i)
    plt.hist(df[column], bins=20, edgecolor='black')
    plt.title(column)
    plt.tight_layout()

plt.show()

# 히스토그램을 그릴 서브플롯 생성
plt.figure(figsize=(15, 15))
for i, column in enumerate(numeric_columns, start=1):
    plt.subplot(5, 5, i)
    plt.boxplot(df[column].dropna())
    plt.title(column)
    plt.tight_layout()

plt.show()

# 바 플롯 그릴 서브플롯 생성
plt.figure(figsize=(15, 15))
for i, column in enumerate(tf_columns, start=1):
    plt.subplot(5, 5, i)  # Adjust the subplot grid as needed
    sns.countplot(x=column, data=df)
    plt.title(f'Countplot of {column}')
    plt.xlabel(column)
    plt.ylabel('Count')

plt.tight_layout()
plt.show()

import seaborn as sns

# 수치형 변수 간의 산점도 그리기
sns.pairplot(df[numeric_columns])
plt.show()